export const TABS = {
  CHATS: 'Chats',
  REQUESTS: 'Request',
};

export const DEFAULT_AVATAR =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA60lEQVR4AcXBsW3EMAxA0R9CM7jPEgY8QUqtoIaNu9SuvYIbNVyBUxxwo2iJpKVTKDhcwfc+vj6/f5g49kF0Xgszxz6IzmthRkgmJBOSFTUn6q0SjfXBzVWZGeuDm6sSqTmRkExIJiQrvVUiNSfqrRKpOTO9VSI1J+qtEgnJhGRCssI/1JxXqDmvEJIJyYRk5dgH0eCut0qk5sz0VonUnOjYB5GQTEgmJCvntRDpyo2aE/VWmVFzZs5rIRKSCcmEZIU/ludGNNYHkZrziuW5MSMkE5IJyYqac/PciHqrvOPYB5GaEwnJhGRCsl/QAz+87qkGxwAAAABJRU5ErkJggg==';
